sylius_resource:
    resources:
        workflow.run:
            driver: doctrine/orm
            classes:
                model: Abderrahim\SyliusWorkflowPlugin\Entity\WorkflowRun
                interface: Abderrahim\SyliusWorkflowPlugin\Entity\WorkflowRunInterface
                repository: Abderrahim\SyliusWorkflowPlugin\Repository\WorkflowRunRepository
