sylius_grid:
    grids:
        workflow_admin_campaign:
            driver:
                name: doctrine/orm
                options:
                    class: '%workflow.model.campaign.class%'
                    repository:
                        method: createQueryBuilder
                        arguments: ['c']
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    label: workflow.ui.name
                    sortable: ~
                status:
                    type: twig
                    label: workflow.ui.status
                    options:
                        template: '@SyliusWorkflowPlugin/admin/workflow_campaign/field/status.html.twig'
                runCount:
                    type: string
                    label: workflow.ui.run_count
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: '@SyliusWorkflowPlugin/admin/workflow_campaign/field/enabled_toggle.html.twig'
            filters:
                status:
                    type: select
                    label: workflow.ui.status
                    form_options:
                        choices:
                            workflow.ui.draft: draft
                            workflow.ui.active: active
                            workflow.ui.paused: paused
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                        label: workflow.ui.new_workflow
                        options:
                            link:
                                route: workflow_admin_campaign_create
                item:
                    edit_canvas:
                        type: update
                        label: workflow.ui.edit_canvas
                        options:
                            link:
                                route: sylius_workflow_admin_canvas
                                parameters:
                                    id: resource.id
                    view_runs:
                        type: show
                        label: workflow.ui.view_runs
                        options:
                            link:
                                route: workflow_admin_run_index
                                parameters:
                                    id: resource.id
                    delete:
                        type: delete
                        options:
                            link:
                                route: workflow_admin_campaign_delete
                                parameters:
                                    id: resource.id
